# Generated by Django 4.2 on 2023-06-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_kategori_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
