# Generated by Django 4.2 on 2023-06-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profil_twitter'),
        ('posts', '0004_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profil', verbose_name='Yazar'),
        ),
    ]
