# Generated by Django 4.2 on 2023-06-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profil_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profil',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profil',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
    ]
