# Generated by Django 4.2 on 2023-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profil_facebook_profil_instagram_profil_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='ppic',
            field=models.ImageField(blank=True, null=True, upload_to='profil_resimleri', verbose_name='Profil Resmi'),
        ),
    ]
