# Generated by Django 4.2 on 2023-06-07 13:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profil_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='ppic',
            field=models.ImageField(blank=True, default=user.models.get_default_profile_image, null=True, upload_to='profil_resimleri', verbose_name='Profil Resmi'),
        ),
    ]
